from unittest import mock

import pytest

from wkafka_mcp import server
from wkafka_mcp.catalog import PatternsCatalog


@pytest.fixture
def catalog():
    with mock.patch.object(PatternsCatalog, "refresh_catalog", return_value=[]):
        return PatternsCatalog()


# --- catalog ---


def test_init_loads_initial_catalog():
    c = PatternsCatalog()
    assert len(c.cached_patterns) == 13
    assert c.cached_patterns[0]["name"] == "basic_json_messaging"


def test_fetch_url_exception(catalog, caplog):
    with mock.patch("urllib.request.urlopen", side_effect=Exception("boom")):
        assert catalog._fetch_url("https://example.com/bad.json") == []


def test_refresh_catalog_merges_sources(catalog):
    official = [{"name": "basic_json_messaging"}]
    community = [{"name": "community_pattern"}]
    with mock.patch.object(catalog, "_fetch_url", side_effect=[official, community]) as mock_fetch:
        result = catalog.refresh_catalog()
    assert mock_fetch.call_count == 2
    assert result[0]["origin"] == "Official"
    assert result[1]["origin"] == "Community"


def test_search_matches_multiple_fields(catalog):
    patterns = [
        {"name": "sasl_authentication", "module": "wkafka", "description": "SASL security"},
        {"name": "image_vision_pipeline", "module": "wkafka", "description": "images"},
    ]
    catalog.cached_patterns = patterns
    assert len(catalog.search("sasl")) == 1
    assert len(catalog.search("image")) == 1


# --- get_catalog ---


def test_get_catalog_returns_shared_singleton():
    server.get_catalog.cache_clear()
    c1 = server.get_catalog()
    c2 = server.get_catalog()
    assert c1 is c2
    server.get_catalog.cache_clear()


# --- blueprints ---


def test_blueprints_contains_all_sections():
    text = server.get_wkafka_architect_blueprints()
    for s in [
        "=== 1. BASIC JSON PRODUCER/CONSUMER",
        "=== 2. IMAGE / VISION PIPELINE",
        "=== 3. YAML CONFIGURATION",
        "=== 4. SASL AUTHENTICATION",
        "=== 5. HEADERS",
        "=== 6. KEY FILTERED CONSUMPTION",
        "=== 7. LEGACY CONTROLLER BRIDGE",
    ]:
        assert s in text
    assert "WKAFKA EXPERT BLUEPRINTS" in text
    assert "read/write" in text.lower()


# --- manual ---


def test_manual_contains_guides():
    text = server.get_wkafka_architect_manual()
    assert "WKAFKA ARCHITECT MANUAL" in text
    assert "PROJECT STRUCTURE RULES" in text
    assert "CORE RULES" in text
    assert "DATA FLOW GUIDE" in text
    assert "MODULE MAP" in text
    assert "REFACTORING A MONOLITH TO WKAFKA" in text
    assert "mermaid" in text
    assert "Generated by WKafka MCP by wisrovi" in text


# --- search tool ---


def test_search_wkafka_pattern_returns_results():
    patterns = [
        {"origin": "Official", "name": "sasl_authentication", "manager": "WKafka", "module": "wkafka", "description": "SASL"},
        {"origin": "Community", "name": "custom_serializer", "manager": "Serializer", "module": "wkafka.serializers.base", "description": "ext"},
    ]
    catalog_mock = mock.MagicMock()
    catalog_mock.search.return_value = patterns
    with mock.patch.object(server, "get_catalog", return_value=catalog_mock):
        text = server.search_wkafka_pattern("sasl")
    assert "sasl_authentication" in text
    assert "Official" in text
    assert "Community" in text


def test_search_wkafka_pattern_no_results():
    catalog_mock = mock.MagicMock()
    catalog_mock.search.return_value = []
    with mock.patch.object(server, "get_catalog", return_value=catalog_mock):
        text = server.search_wkafka_pattern("zzz_nope")
    assert "No pattern matching 'zzz_nope' was found" in text


# --- deploy scaffolding ---


def test_deploy_wkafka_scaffolding_relative_path_rejected():
    text = server.deploy_wkafka_scaffolding("relative/path")
    assert text.startswith("Error:")
    assert "absolute path" in text


def test_deploy_wkafka_scaffolding_creates_project(tmp_path):
    target = str(tmp_path / "deployed")
    result = server.deploy_wkafka_scaffolding(target, project_name="MyKafka", scaffold_type="vision_pipeline")
    assert result.startswith("Success:")
    assert "MyKafka" in result
    assert (tmp_path / "deployed" / "main.py").exists()
    assert (tmp_path / "deployed" / "config" / "settings.py").exists()
    assert (tmp_path / "deployed" / "consumers" / "consumer.py").exists()
    assert (tmp_path / "deployed" / "producers" / "producer.py").exists()


def test_deploy_wkafka_scaffolding_exception_returns_error(tmp_path):
    target = str(tmp_path / "blocked")
    with mock.patch.object(server.TemplateGenerator, "get_folders", side_effect=OSError("disk full")):
        text = server.deploy_wkafka_scaffolding(target)
    assert text == "Error: disk full"


# --- generate_from_pattern ---


def test_generate_from_pattern_not_found(tmp_path):
    target = str(tmp_path / "gen")
    text = server.generate_from_pattern("nope", target)
    assert "not found" in text


# --- validate_kafka_config ---


def test_validate_kafka_config_missing_bootstrap():
    text = server.validate_kafka_config('client_id="x"')
    assert "Missing bootstrap_servers" in text


def test_validate_kafka_config_hardcoded_credential():
    text = server.validate_kafka_config('bootstrap_servers="localhost:9092" sasl_plain_password="secret"')
    assert "Hardcoded credential" in text


def test_validate_kafka_config_ok():
    text = server.validate_kafka_config('bootstrap_servers="localhost:9092"')
    assert "validated successfully" in text


# --- CLI run modes ---


def test_run_stdio_uses_stdio_transport():
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.run_stdio()
    mock_run.assert_called_once_with(transport="stdio")


def test_run_sse_uses_sse_transport():
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.run_sse()
    mock_run.assert_called_once_with(transport="sse")


def test_print_config_to_stdout(capsys):
    server.print_config(write_file=False)
    captured = capsys.readouterr()
    assert "wkafka-mcp" in captured.out
    assert "QUICK INSTALL COMMANDS" in captured.out


def test_print_config_saves_file(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    server.print_config(write_file=True)
    assert (tmp_path / ".agents" / "wkafka-mcp.json").exists()


def test_main_config_saves_file(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    monkeypatch.setattr(server.sys, "argv", ["wkafka-mcp", "config"])
    server.main()
    assert (tmp_path / ".agents" / "wkafka-mcp.json").exists()


def test_main_run_uses_stdio(monkeypatch):
    monkeypatch.setattr(server.sys, "argv", ["wkafka-mcp", "run"])
    with mock.patch.object(server.mcp, "run") as mock_run:
        server.main()
    mock_run.assert_called_once_with(transport="stdio")
