"""Advanced scaffolding templates for professional WKafka development."""


class TemplateGenerator:
    """Provides professional boilerplate for WKafka projects following wisrovi standards."""

    @staticmethod
    def get_supported_types() -> list:
        """Return the list of supported scaffold types."""
        return ["standard", "vision_pipeline", "full_service"]

    @staticmethod
    def get_folders(scaffold_type: str) -> list:
        """Return the folder layout for the requested scaffold type."""
        if scaffold_type == "vision_pipeline":
            return ["config", "models", "consumers", "producers", "tests", ".wkafka"]
        if scaffold_type == "full_service":
            return [
                "config",
                "models",
                "consumers",
                "producers",
                "serializers",
                "tests",
                "examples",
                ".wkafka",
                "scripts",
                ".github/workflows",
            ]
        return ["config", "models", "consumers", "producers", "tests", ".wkafka"]

    @staticmethod
    def get_files_blueprint(
        scaffold_type: str, project_name: str = "wkafka_project"
    ) -> dict:
        """Return filenames and their professional template content."""
        settings_template = (
            "import os\n\n"
            "# Centralized Kafka connection settings (wisrovi standard).\n"
            "# Prefer environment variables for all credentials.\n\n"
            'BOOTSTRAP_SERVERS = os.getenv("KAFKA_SERVER", "localhost:9092")\n'
            'CLIENT_ID = os.getenv("KAFKA_CLIENT_ID", "wkafka-service")\n'
            'ACKS = int(os.getenv("KAFKA_ACKS", "1"))\n\n'
            "# Security (SASL/SSL) - leave empty for plain local development.\n"
            'SECURITY_PROTOCOL = os.getenv("KAFKA_SECURITY_PROTOCOL")\n'
            'SASL_MECHANISM = os.getenv("KAFKA_SASL_MECHANISM")\n'
            'SASL_USERNAME = os.getenv("KAFKA_SASL_USERNAME")\n'
            'SASL_PASSWORD = os.getenv("KAFKA_SASL_PASSWORD")\n'
        )

        message_model = (
            "from pydantic import BaseModel\n\n\n"
            "class Order(BaseModel):\n"
            '    """Example message schema. WKafka deserializes JSON into this."""\n'
            "    id: int\n"
            "    customer: str\n"
            "    amount: float\n"
        )

        producer_template = (
            "from wkafka import WKafka\n"
            "from config.settings import ACKS, BOOTSTRAP_SERVERS, CLIENT_ID, SASL_MECHANISM, SASL_PASSWORD, SASL_USERNAME, SECURITY_PROTOCOL\n\n"
            "# Build the WKafka orchestrator. Extra kwargs are forwarded to kafka-python.\n"
            "extra = {}\n"
            "if SECURITY_PROTOCOL:\n"
            "    extra.update(\n"
            "        security_protocol=SECURITY_PROTOCOL,\n"
            "        sasl_mechanism=SASL_MECHANISM,\n"
            "        sasl_plain_username=SASL_USERNAME,\n"
            "        sasl_plain_password=SASL_PASSWORD,\n"
            "    )\n"
            "kafka = WKafka(bootstrap_servers=BOOTSTRAP_SERVERS, client_id=CLIENT_ID, acks=ACKS, **extra)\n\n"
            "with kafka.producer() as p:\n"
            '    p.send("orders", value={"id": 1, "customer": "alice", "amount": 99.9}, key="order-1", format="json")\n'
            '    print("Message sent.")\n'
        )

        consumer_template = (
            "from wkafka import WKafka\n"
            "from config.settings import BOOTSTRAP_SERVERS, CLIENT_ID\n\n"
            "kafka = WKafka(bootstrap_servers=BOOTSTRAP_SERVERS, client_id=CLIENT_ID)\n\n"
            '@kafka.consumer(topic="orders", format="json", auto_offset_reset="earliest")\n'
            "def handle_order(msg):\n"
            '    print(f"New order: {msg.value} (offset {msg.offset})")\n'
            '    # return {"exit": True}  # graceful stop after processing\n\n'
            'if __name__ == "__main__":\n'
            "    kafka.run_consumers(block=True)\n"
        )

        test_template = (
            "import pytest\n\n"
            "def test_producer_and_consumer_import():\n"
            "    import wkafka\n"
            "    from wkafka import WKafka\n"
            "    from wkafka.core.models import Message\n"
            "    assert WKafka is not None\n"
            "    assert Message is not None\n"
        )

        readme_footer = "Generated by WKafka MCP by wisrovi"

        blueprint = {
            "main.py": (
                "from wkafka import WKafka\n"
                "from config.settings import BOOTSTRAP_SERVERS, CLIENT_ID\n\n"
                "kafka = WKafka(bootstrap_servers=BOOTSTRAP_SERVERS, client_id=CLIENT_ID)\n\n\n"
                "def main():\n"
                '    """Service entrypoint: register consumers and run."""\n'
                '    print(f"{CLIENT_ID} running. Press Ctrl+C to stop.")\n'
                "    # Import consumers so decorators register them.\n"
                "    import consumers  # noqa: F401\n"
                "    kafka.run_consumers(block=True)\n\n\n"
                'if __name__ == "__main__":\n'
                "    main()\n"
            ),
            "config/settings.py": settings_template,
            "models/message.py": message_model,
            "producers/producer.py": producer_template,
            "consumers/consumer.py": consumer_template,
            "tests/test_imports.py": test_template,
            "README.md": (
                f"# {project_name}\n\n"
                "Kafka service built with WKafka (wisrovi standard).\n\n"
                "## Run\n\n"
                "```bash\n"
                "python main.py\n"
                "```\n\n"
                "## Structure\n\n"
                "- `config/` - centralized connection settings (env-driven)\n"
                "- `models/` - typed message schemas\n"
                "- `producers/` - producers using `with kafka.producer()`\n"
                "- `consumers/` - handlers decorated with `@kafka.consumer()`\n\n"
                f"{readme_footer}\n"
            ),
        }

        if scaffold_type == "vision_pipeline":
            blueprint.update(
                {
                    "producers/frame_capture.py": (
                        "import cv2\n"
                        "from wkafka import WKafka\n\n"
                        "kafka = WKafka()\n\n"
                        "def stream_frames(source: int = 0):\n"
                        "    cap = cv2.VideoCapture(source)\n"
                        "    with kafka.producer() as p:\n"
                        "        while True:\n"
                        "            ok, frame = cap.read()\n"
                        "            if not ok:\n"
                        "                break\n"
                        '            p.send("camera-frames", value=frame, format="image")\n'
                    ),
                    "consumers/inference.py": (
                        "from wkafka import WKafka\n\n"
                        "kafka = WKafka()\n\n"
                        '@kafka.consumer(topic="camera-frames", format="image")\n'
                        "def handle_frame(msg):\n"
                        "    # msg.value is a numpy.ndarray (BGR frame)\n"
                        '    print(f"Frame received, shape={msg.value.shape}")\n'
                    ),
                }
            )

        if scaffold_type == "full_service":
            blueprint.update(
                {
                    "serializers/custom_serializer.py": (
                        "from wkafka.serializers.base import Serializer\n\n"
                        "class CustomSerializer(Serializer):\n"
                        "    def serialize(self, value, **kwargs):\n"
                        "        return str(value).encode('utf-8')\n\n"
                        "    def deserialize(self, value, **kwargs):\n"
                        "        return value.decode('utf-8')\n"
                    ),
                    "scripts/run_tests.sh": (
                        "#!/bin/bash\n"
                        "pytest tests/\n"
                    ),
                    ".github/workflows/ci.yml": (
                        "name: CI\n"
                        "on: [push, pull_request]\n"
                        "jobs:\n"
                        "  test:\n"
                        "    runs-on: ubuntu-latest\n"
                        "    steps:\n"
                        "      - uses: actions/checkout@v4\n"
                        "      - name: Set up Python\n"
                        "        uses: actions/setup-python@v5\n"
                        "        with:\n"
                        "          python-version: '3.13'\n"
                        "      - name: Install dependencies\n"
                        "        run: pip install pytest wkafka\n"
                        "      - name: Run tests\n"
                        "        run: pytest tests/\n"
                    ),
                }
            )

        return blueprint
